In [1]:
#list
[4,5,6]

[4, 5, 6]

In [3]:
#tuple
(4,5,6)

(4, 5, 6)

In [4]:
#sets
{2,3,4,5,6,"s","d","s",4,7}

{2, 3, 4, 5, 6, 7, 'd', 's'}

In [5]:
#dictionary
d={"a":2,"b":5,"c":9}
d["b"]

5

In [6]:
#loop and index
for i in range(4):
    print(i)

0
1
2
3


In [1]:
#PyTorch
import torch
print(torch.__version__)

1.6.0


In [10]:
# Create a rank 1 tensor from a Python list
a = torch.tensor([1,2,3])
print ('Here is a:')
print(a)
print('type(a):',type(a))
print('rank of a:',a.dim())
print('a.shape:',a.shape)

#Access elements using square brackets
print()
print('a[0]:',a[0])
print('type(a[0]):',type(a[0].item()))

#Mutate elements using square brackets
a[1]=10
print()
print('a after mutating:')
print(a)

Here is a:
tensor([1, 2, 3])
type(a): <class 'torch.Tensor'>
rank of a: 1
a.shape: torch.Size([3])

a[0]: tensor(1)
type(a[0]): <class 'int'>

a after mutating:
tensor([ 1, 10,  3])


In [13]:
# Create a two-dimensional tensor 
b= torch.tensor([[1,2,3],[4,5,6]])
print ('Here is b:')
print(b)
print('rank of b:',b.dim())
print('b.shape:',b.shape)

#Access elements from a multidimensional tensor
print()
print('b[0,1]:',b[0,1])
print('b[1,2]:',b[1,2])

#Mutate elements of a multidimensional tensor
b[1,1]=1000
print()
print('a after mutating:')
print(b)

Here is b:
tensor([[1, 2, 3],
        [4, 5, 6]])
rank of b: 2
b.shape: torch.Size([2, 3])

b[0,1]: tensor(2)
b[1,2]: tensor(6)

a after mutating:
tensor([[   1,    2,    3],
        [   4, 1000,    6]])


In [16]:
# Create a tensor of all zeros
a = torch.zeros(2,3)
print('tensor of zeros:')
print(a)

#Create a tensor of all ones
b = torch.ones(1,2)
print('\ntensor of ones:')
print(b)

#Create a 4x4 identity matrix
c = torch.eye(4)
print('\ntensor matrix:')
print(c)

#Tensor of random values
d = torch.rand(5,6)
print('\nrandom tensor:')
print(d)

tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor of ones:
tensor([[1., 1.]])

tensor matrix:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

random tensor:
tensor([[0.0878, 0.4673, 0.8756, 0.5894, 0.3757, 0.7529],
        [0.0543, 0.4348, 0.9659, 0.6861, 0.9748, 0.3158],
        [0.4606, 0.1280, 0.5095, 0.2364, 0.5711, 0.8712],
        [0.0031, 0.2691, 0.7556, 0.2726, 0.2382, 0.1109],
        [0.5091, 0.4566, 0.3392, 0.4177, 0.3374, 0.4066]])


In [17]:
#Let torch choose the datatype
x0 = torch.tensor([1,2])#List of integers
x1 = torch.tensor([1.,2.,])#List of floats
x2 = torch.tensor([1.,2])#Mixed list
print('datatype when torch choose for us:')
print('List of integers:', x0.dtype)
print('List of floats:', x1.dtype)
print('Mixed list:', x2.dtype)

#Force a particular datatype
y0 = torch.tensor([1,2], dtype=torch.float32)#32-bit float
y1 = torch.tensor([1,2], dtype=torch.int32)#32-bit(signed) integer
y2 = torch.tensor([1,2], dtype=torch.int64)#64-bit(signed) integer
print('\ndatatype when we force a datatype:')
print('32-bit float:', y0.dtype)
print('32-bit integer:', y1.dtype)
print('64-bit integer:', y2.dtype)

datatype when torch choose for us:
List of integers: torch.int64
List of floats: torch.float32
Mixed list: torch.float32

datatype when we force a datatype:
32-bit float: torch.float32
32-bit integer: torch.int32
64-bit integer: torch.int64


In [19]:
x0 = torch.eye(3, dtype = torch.int64)
x1 = x0.float() #Cast to 32-bit float
x2 = x0.double()#Cast to 64-bit float
x3 = x0.to(torch.float32) #Alternative way to cast to 32-bit float
x4 = x0.to(torch.float64) #Alternative way to cast to 64-bit float
print('x0:',x0.dtype)
print('x1:',x1.dtype)
print('x2:',x2.dtype)
print('x3:',x3.dtype)
print('x4:',x4.dtype)

x0: torch.int64
x1: torch.float32
x2: torch.float64
x3: torch.float32
x4: torch.float64


In [22]:
x0 = torch.eye(3,dtype = torch.float64)# Shape (3,3), dtype torch.float64
x1 = torch.zeros_like(x0)# Shape (3,3), dtype torch.float64
x2 = x0.new_zeros(4,5)# Shape (4,5), dtype torch.float64
x3 = torch.ones(6,7).to(x0)# Shape (6,7), dtype torch.float64
print('x0 shape is %r, dtype is %r' % (x0.shape, x0.dtype))
print('x1 shape is %r, dtype is %r' % (x1.shape, x1.dtype))
print('x2 shape is %r, dtype is %r' % (x2.shape, x2.dtype))
print('x3 shape is %r, dtype is %r' % (x3.shape, x3.dtype))

x0 shape is torch.Size([3, 3]), dtype is torch.float64
x1 shape is torch.Size([3, 3]), dtype is torch.float64
x2 shape is torch.Size([4, 5]), dtype is torch.float64
x3 shape is torch.Size([6, 7]), dtype is torch.float64


In [24]:
# Tensor indexing
a = torch.tensor([0,11,22,33,44,55,66])
print(0,a)     # Original tensor
print(1,a[2:6])# Elements between index 2 and 5
print(2,a[3:]) # Elements after index 3
print(3,a[:4]) # Elements before index 4 
print(4,a[:])  # All elements
print(5,a[1:5:3]) # Every third element between indices 1 and 5
print(6, a[:-1]) # All but last element
print(7,a[-4::2]) # Every second element, starting from the fourth-last

0 tensor([ 0, 11, 22, 33, 44, 55, 66])
1 tensor([22, 33, 44, 55])
2 tensor([33, 44, 55, 66])
3 tensor([ 0, 11, 22, 33])
4 tensor([ 0, 11, 22, 33, 44, 55, 66])
5 tensor([11, 44])
6 tensor([ 0, 11, 22, 33, 44, 55])
7 tensor([33, 55])


In [27]:
#Create the following rank 2 tensor with shape (3,4)
#[[1,2,3,4]
#[5,6,7,8]
#[9,10,11,12]]
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Original tensor')
print(a)
print('shape:',a.shape)

#Get row 2, and all columns.
print('\nSingle row:')
print(a[1,:])
print(a[1]) 
print('shape:',a[1].shape)

print('\nSingle column:')
print(a[:,1])
print('shape:',a[:,1].shape)

#Get the first two rows and the last three columns
print('\First two rows, last two columns: ')
print(a[::2,1:3])
print('shape:',a[::2,1:3].shape)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])

Single row:
tensor([5, 6, 7, 8])
tensor([5, 6, 7, 8])
shape: torch.Size([4])

Single column:
tensor([ 2,  6, 10])
shape: torch.Size([3])
\First two rows, last two columns: 
tensor([[ 2,  3],
        [10, 11]])
shape: torch.Size([2, 2])


In [29]:
#Create the following rank 2 tensor with shape(3,4)
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Original tensor')
print(a)

row_r1 = a[1,:] # Rank 1 view of the second row of a
row_r2 = a[1:2,:] #Rank 2 view of the second row of a
print('\nTwo ways of accessing a single row:')
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

#We can make the samw distinction when accessing columns::
col_r1 = a[:,1]
col_r2 = a[:, 1:2]
print('\nTwo ways of accessing a single column:')
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Two ways of accessing a single row:
tensor([5, 6, 7, 8]) torch.Size([4])
tensor([[5, 6, 7, 8]]) torch.Size([1, 4])

Two ways of accessing a single column:
tensor([ 2,  6, 10]) torch.Size([3])
tensor([[ 2],
        [ 6],
        [10]]) torch.Size([3, 1])


In [30]:
#Create a tensor, a slice, and a clone of a slice
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Before mutating')
print(a)
print(b)
print(c)

Before mutating
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 3, 4])
tensor([2, 3, 4])


In [31]:
#Create the following rank 2 tensor with shape (3,4)
#[[1,2,3,4]
#[5,6,7,8]
#[9,10,11,12]]
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Original tensor')
print(a)

#Create a new tensor of shape (5,4 ) by reordering rows from a:
#-First two rows same as the first row of a
#-Third row is the same as the last row of a
#-Fourth and Fifth rows are the same as the second row from a
idx = [0,0,2,1,1] #index arrays can be Python lists of integers
print('\nReordered rows:')
print(a[idx])

#Create a new tensor of shape (3,4) by reversing the columns from a 
idx = torch.tensor([3,2,1,0])
print('\nReordered columns:')
print(a[:,idx])

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reordered rows:
tensor([[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]])

Reordered columns:
tensor([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]])


In [33]:
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Original tensor')
print(a)

idx = [0,1,2]
print('\nGet the diagonal:')
print(a[idx,idx])

#Modify the diagonal
a[idx,idx] = torch.tensor([11,22,33])
print('\nAfter setting the diagonal:')
print(a)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Get the diagonal:
tensor([ 1,  6, 11])

After setting the diagonal:
tensor([[11,  2,  3,  4],
        [ 5, 22,  7,  8],
        [ 9, 10, 33, 12]])


In [37]:
#Create a new tensor from which will select elements
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Original tensor')
print(a)

#Take on elements from each row of a:
#from row 0, take element 1;
#from row 1, take element 2;
#from row 2, take element 1;
#from row 3, take element 0;
idx0 = torch.arange(a.shape[0])
idx1 = torch.tensor([1,2,1,0])
print('\nSelect one element from each row:')
print(a[idx0,idx1])

#Now set each of those elements to zero
a[idx0,idx1] = 0
print('\nAfter modifying one element from each row:')
print(a)

Original tensor
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Select one element from each row:
tensor([ 2,  6,  8, 10])

After modifying one element from each row:
tensor([[ 1,  0,  3],
        [ 4,  5,  0],
        [ 7,  0,  9],
        [ 0, 11, 12]])


In [39]:
#Boolean tensor indexing
a = torch.tensor([[1,2],[3,4],[5,6]])
print('Original tensor')
print(a)

#Find the elements of a that are bigger than 3. The mask has the same shape as a,
#where each element of mask tells whether the corresponding element of a is greater than three
mask = (a>3)
print('\nMask tensor:')
print(mask)

#We can use the mask to construck a rank-1 tensor containing the elements of a that are selected by the mask
print('\nSelecting elements with the mask:')
print(a[mask])

#We can also use boolean masks to modify tensors; for example this sets all elements <=3 to zero:
a[a <= 3] = 0
print('\nAfter modifying with a mask:')
print(a)

Original tensor
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Mask tensor:
tensor([[False, False],
        [False,  True],
        [ True,  True]])

Selecting elements with the mask:
tensor([4, 5, 6])

After modifying with a mask:
tensor([[0, 0],
        [0, 4],
        [5, 6]])


In [40]:
#Reshaping operations
x0 = torch.tensor([[1,2,3,4],[5,6,7,8]])
print('Original tensor:')
print(x0)
print('shape:',x0.shape)

#Flatten x0 into a rank 1 vector of shape (8,)
x1 = x0.view(8)
print('\nFlatten tensor:')
print(x1)
print('shape:',x1.shape)

#Convert x1 to a rank 2 "row vector" of shape(1,8)
x2 = x1.view(1,8)
print('\nRow vector:')
print(x2)
print('shape:',x2.shape)

#Convert x1 to a rank 2 "column vector" of shape(8,1)
x3 = x2.view(8,1)
print(x3)
print('shape:',x3.shape)

#Convert x1 to a rank 3 tensor of shape(2,2,2):
x4 = x3.view(2,2,2)
print('\nRank 3 tensor:')
print(x4)
print('shape:',x4.shape)


Original tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
shape: torch.Size([2, 4])

Flatten tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8])
shape: torch.Size([8])

Row vector:
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
shape: torch.Size([1, 8])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
shape: torch.Size([8, 1])

Rank 3 tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
shape: torch.Size([2, 2, 2])


In [41]:
#We can reuse these functions for tensors of different shapes
x0 = torch.tensor([[1,2,3],[4,5,6]])
x1 = x0.view(-1,)
x2 = x0.view(-1,2)

print('x0:')
print(x0)

print('x1:')
print(x1)

print('x2:')
print(x2)


x0:
tensor([[1, 2, 3],
        [4, 5, 6]])
x1:
tensor([1, 2, 3, 4, 5, 6])
x2:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [42]:
x = torch.tensor([[1,2,3],[4,5,6]])
x_flat = x.view(-1)
print('x before modifying:')
print(x)
print('x_flat before modifying:')
print(x_flat)

x[0,0] = 10
x_flat[1] = 20

print('\nx after modifying:')
print(x)
print('x_flat after modifying:')
print(x_flat)

x before modifying:
tensor([[1, 2, 3],
        [4, 5, 6]])
x_flat before modifying:
tensor([1, 2, 3, 4, 5, 6])

x after modifying:
tensor([[10, 20,  3],
        [ 4,  5,  6]])
x_flat after modifying:
tensor([10, 20,  3,  4,  5,  6])


In [43]:
#Swapping axes
x = torch.tensor([[1,2,3],[4,5,6]])
print('Original matrix:')
print(x)
print('\nTransposing with view DOES NOT WORK!')
print(x.view(3,2))
print('\nTransposed matrix')
print(torch.t(x))
print(x.t())

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transposing with view DOES NOT WORK!
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Transposed matrix
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [45]:
#Create a tensor of shape(2,3,4)
x0 = torch.tensor([
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]],
    [[13,14,15,16],
     [17,18,19,20],
     [21,22,23,24]]])
print('Original tensor:')
print(x0)
print('shape:',x0.shape)

#Swap axes 1 and 2; shape is (2,4,3)
x1 = x0.transpose(1,2)
print('\nSwap axes 1 and 2:')
print(x1)
print(x1.shape)

#Permute axes; the argument(1,2,0)means;
#-Make the old dimension 1 appear at dimension 0;
#-Make the old dimension 2 appear at dimension 1;
#-Make the old dimension 0 appear at dimension 2;
x2 = x0.permute(1,2,0)
print('\nPermute axes')
print(x2)
print('shape:',x2.shape)

Original tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
shape: torch.Size([2, 3, 4])

Swap axes 1 and 2:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
torch.Size([2, 4, 3])

Permute axes
tensor([[[ 1, 13],
         [ 2, 14],
         [ 3, 15],
         [ 4, 16]],

        [[ 5, 17],
         [ 6, 18],
         [ 7, 19],
         [ 8, 20]],

        [[ 9, 21],
         [10, 22],
         [11, 23],
         [12, 24]]])
shape: torch.Size([3, 4, 2])


In [47]:
x0 = torch.randn(2,3,4)
try:
    #This sequence of reshape operations will crash
    x1 = x0.transpose(1,2).view(8,3)
except RuntimeError as e:
    print(type(e),e)
    
#We can slove this problem using either .contiguous or .reshape()
x1 = x0.transpose(1,2).contiguous().view(8,3)
x2 = x0.transpose(1,2).reshape(8,3)
print('x1 shape:',x1.shape)
print('x1 shape:',x1.shape)

<class 'RuntimeError'> view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
x1 shape: torch.Size([8, 3])
x1 shape: torch.Size([8, 3])


In [48]:
#Tensor operations
#Elementwise operations
x = torch.tensor([[1,2,3,4]],dtype = torch.float32)
y = torch.tensor([[5,6,7,8]],dtype = torch.float32)

#Elementwise sum; all give the same result
print('Elemtentwise sum:')
print(x+y)
print(torch.add(x,y))
print(x.add(y))

#Elementwise difference
print('\nElemtentwise difference:')
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

#Elementwise product
print('\nElemtentwise product:')
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

#Elementwise division
print('\nElemtentwise division:')
print(x/y)
print(torch.div(x,y))
print(x.div(y))

#Elementwise power
print('\nElemtentwise power:')
print(x**y)
print(torch.pow(x,y))
print(x.pow(y))

Elemtentwise sum:
tensor([[ 6.,  8., 10., 12.]])
tensor([[ 6.,  8., 10., 12.]])
tensor([[ 6.,  8., 10., 12.]])

Elemtentwise difference:
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])

Elemtentwise product:
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])

Elemtentwise division:
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])

Elemtentwise power:
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])


In [49]:
x = torch.tensor([[1,2,3,4]],dtype=torch.float32)
print('Square root:')
print(torch.sqrt(x))
print(x.sqrt())

print('n\Trig functions:')
print(torch.sin(x))
print(x.sin())
print(torch.cos(x))
print(x.cos())

Square root:
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
n\Trig functions:
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])


In [51]:
#Reduction operations
x = torch.tensor([[1,2,3],
                 [4,5,6]],dtype=torch.float32)
print('Original tensor:')
print(x)

print('\nSum over entire tensor:')
print(torch.sum(x))
print(x.sum())

print('\nSum of each row:')
print(torch.sum(x,dim=0))
print(x.sum(dim=0))

print('\nSum of each column')
print(torch.sum(x,dim=1))
print(x.sum(dim=1))

Original tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum over entire tensor:
tensor(21.)
tensor(21.)

Sum of each row:
tensor([5., 7., 9.])
tensor([5., 7., 9.])

Sum of each column
tensor([ 6., 15.])
tensor([ 6., 15.])


In [ ]:
#Matrix operations
v = torch.tensor([9,10],dtype=torch.float32)
w = torch.tensor([11,12],dtype=torch.float32)

print('Dot products:')
print(torch.dot(v,w))
print(v.dot(w))

x = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
y = torch.tensor([[5,6],[7,8]],dtype=torch.float32)
print('\nMatrix-matrix product:')
print(torch.mul(x,y))
print(x.mul(y))

print('\nMatrix-vector product with torch.mv(rank 1 output)')
print(torch.mv(x,v))
print(x.mv(v))

In [53]:
x = torch.tensor([[2,4,3,5],[3,3,5,2]],dtype=torch.float32)
print('Original tensor:')
print(x)
print(x,x.shape)

#Finding the overall minimum only returns a single value
print('\nOverall minimum:', x.min())

col_min_vals,col_min_idxs = x.min(dim=0)
print('\nMinimum along each column:')
print('values:', col_min_vals)
print('idxs:', col_min_idxs

row_min_vals,row_min_idxs = x.min(dim=1)
print('\nMinimum along each row:')
print('values:', row_min_vals)
print('idxs:', row_min_idxs)



Original tensor:
tensor([[2., 4., 3., 5.],
        [3., 3., 5., 2.]])
tensor([[2., 4., 3., 5.],
        [3., 3., 5., 2.]]) torch.Size([2, 4])

Overall minimum: tensor(2.)

Minimum along each column:
values: tensor([2., 3., 3., 2.])
idxs: tensor([0, 1, 0, 1])

Minimum along each row:
values: tensor([2., 2.])
idxs: tensor([0, 3])


In [54]:
x = torch.randn(128,10,3,64,64)
print(x.shape)

x = x.mean(dim=1)
print(x.shape)

x = x.sum(dim=2)
print(x.shape)

x = x.mean(dim=1,keepdim=True)
print(x.shape)

torch.Size([128, 10, 3, 64, 64])
torch.Size([128, 3, 64, 64])
torch.Size([128, 3, 64])
torch.Size([128, 1, 64])


In [ ]:
x = torch.tensor([[2,4,3,5],[3,3,5,2]],dtype=torch.float32)
print('Original tensor:')
print(x)
print(x,x.shape)

#Finding the overall minimum only returns a single value
print('\nOverall minimum:', x.min())

col_min_vals,col_min_idxs = x.min(dim=0)
print('\nMinimum along each column:')
print('values:', col_min_vals)
print('idxs:', col_min_idxs)

row_min_vals,row_min_idxs = x.min(dim=1)
print('\nMinimum along each row:')
print('values:', row_min_vals)
print('idxs:', row_min_idxs)

In [56]:
#Broadcasting
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = torch.tensor([1,0,1])
y = torch.zeros_like(x)

for i in range(4):
    y[i,:] = x[i,:]+v
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [57]:
vv = v.repeat((4,1))
print(vv)


tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])


In [58]:
y = x + vv
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [59]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = torch.tensor([1,0,1])
y = x+v
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [62]:
v = torch.tensor([1,2,3])
w = torch.tensor([4,5])
print(v.view(3,1) * w)

tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])


In [63]:
if torch.cuda.is_available:
    print('Python can use GPUs!')
else:
    print('Python cannot use GPUs.')

Python can use GPUs!


In [16]:
#Modifying the matrix operations
v = torch.tensor([9,10],dtype=torch.float32)
w = torch.tensor([11,12],dtype=torch.float32)

print('Dot products:')
print(v.dot(v*w)-w.dot(v))

x = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
y = torch.tensor([[5,6],[7,8]],dtype=torch.float32)
print('\nMatrix-matrix product:')
print(torch.mm(x,y))
print(y.mm(x*y))

Dot products:
tensor(1872.)

Matrix-matrix product:
tensor([[19., 22.],
        [43., 50.]])
tensor([[151., 252.],
        [203., 340.]])


In [17]:
#Modifying the code
x = torch.tensor([[2,4,3,5],[3,3,5,2]],dtype=torch.float32)
print('Original tensor:')
print(x)
print(x,x.shape)

#Finding the overall maximum only returns a single value
print('\nOverall maximum:', x.max())

col_max_vals,col_max_idxs = x.max(dim=0)
print('\nMaximum along each column:')
print('values:', col_max_vals)
print('idxs:', col_max_idxs)

row_max_vals,row_max_idxs = x.max(dim=1)
print('\nMaximum along each row:')
print('values:', row_max_vals)
print('idxs:', row_max_idxs)

Original tensor:
tensor([[2., 4., 3., 5.],
        [3., 3., 5., 2.]])
tensor([[2., 4., 3., 5.],
        [3., 3., 5., 2.]]) torch.Size([2, 4])

Overall maximum: tensor(5.)

Maximum along each column:
values: tensor([3., 4., 5., 5.])
idxs: tensor([1, 0, 1, 0])

Maximum along each row:
values: tensor([5., 5.])
idxs: tensor([3, 2])


In [45]:
#Modifying the operations
x = torch.tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
v = torch.tensor([1,0,1,5])
y = torch.zeros_like(x)

for i in range(4):
    y[i,:] = x[i,:]*v
print(y)

tensor([[ 1,  0,  3, 20],
        [ 4,  0,  6, 35],
        [ 7,  0,  9, 50],
        [10,  0, 12, 65]])


In [42]:
#Modifying the operations
v = torch.tensor([[1,2],[1,3]])
w = torch.tensor([4,5])
print(v.view(2,2) * w)

tensor([[ 4, 10],
        [ 4, 15]])


In [51]:
#Modifying the operations

x0 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x1 = x0.view(-1,3)
x2 = x1.view(-1,)


print('x0:')
print(x0)

print('x1:')
print(x1)

print('x2:')
print(x2)


x0:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x1:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x2:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
